### PR TITLE
Use statuses transition information from server

### LINKED ISSUE #16: Cannot change booking status
## Symptoms
In edit booking modal, it is not possible to change the existing bookings status, such as from "Scheduled" to something else.

## How to reproduce
- Create new booking
- Open that booking
- Select some change status action in booking modal
- Press "Save"
- Observe symptom

## Cause
For setting new booking status, the client must send transition name, not new booking status name. Now the client is sending status name which sent as `transition`, but there is no transition with that name.

## Recommended Solution
Use transition map from backend instead of hardcoded client's status -> status map. Each action in UI will correspond to transition which will simplify what data should be sent.

### PR DESCRIPTION
**Pull request by romalytvynenko**
fixes #16

### CODE REVIEW

File: src/components/BookingEditor.js [hunk 1]
```diff
@@ -81,22 +82,7 @@ export default function CfBookingEditor (AbstractEntityModalEditor, {mapState, m
...
-        actionsMap: {
-          'in_cart': ['pending'],
-          'draft': ['pending'],
-          'pending': ['approved', 'cancelled'],
-          'approved': ['scheduled'],
-          'scheduled': ['draft', 'pending', 'cancelled'],
-          'cancelled': ['in_cart', 'draft', 'pending', 'approved', 'scheduled'],
-          'completed': ['in_cart', 'draft', 'pending', 'approved', 'scheduled'],
-        }
+        foundClients: []
```
Comment (XedinUnknown) [inline src/components/BookingEditor.js]: What is the meaning of this property?

File: src/components/BookingEditor.js [hunk 2]
```diff
@@ -129,21 +115,26 @@ export default function CfBookingEditor (AbstractEntityModalEditor, {mapState, m
         services: state => state.services,
       }),
 
+      statusStyle () {
```
Comment (XedinUnknown) [inline src/components/BookingEditor.js]: What does this do?

File: src/components/BookingEditor.js [hunk 3]
```diff
@@ -129,21 +115,26 @@ export default function CfBookingEditor (AbstractEntityModalEditor, {mapState, m
...
        *
-       * @see https://aventura.atlassian.net/wiki/spaces/EDDBK/pages/59751681/Status+Terms
-       *
-       * @return {array}
+       * @return {object}
        */
-      availableActions () {
-        if (!this.model.id) return []
-        return this.actionsMap[this.model.status] || []
+      transitionsMap () {
```
Comment (XedinUnknown) [inline src/components/BookingEditor.js]: Explain more about what this does. Map of available transitions? To what do they map?

File: src/components/BookingEditor.js [hunk 4]
```diff
@@ -129,21 +115,26 @@ export default function CfBookingEditor (AbstractEntityModalEditor, {mapState, m
...
+        return this.state.statusTransitions
       },
 
-      statusStyle () {
-        return this.helpers.statusStyle(this.model.status)
+      /**
+       * Map of available translated transitions labels
```
Comment (XedinUnknown) [inline src/components/BookingEditor.js]: Map of labels to what?

File: src/transformers/BookingTransformer.js [hunk 5]
```diff
@@ -19,12 +19,10 @@ export default class BookingTransformer extends Transformer {
       model['client'] = model['client'].id
       return model
     },
-    newStatus: (model) => {
-      if (model['newStatus']) {
-        model['transition'] = model['newStatus']
+    transition: (model) => {
```
Comment (XedinUnknown) [inline src/transformers/BookingTransformer.js]: What does this do?

File: src/transformers/BookingTransformer.js [hunk 6]
```diff
@@ -10,33 +10,83 @@ export default class BookingTransformer extends Transformer {
    * @property {object} rules
    */
   rules = {
+    /**
+     * Remove service information and left only service's id for sending to API.
+     *
+     * @param {object} model Model to transform
+     *
+     * @return {object} Transformed model
```
Comment (XedinUnknown) [inline src/transformers/BookingTransformer.js]: @mecha, the resource ID and the service ID are not the same thing, AFAIK. Can you please take a look at this code to determine its correctness? We can all then discuss the right way, if needed.

Comment (mecha) [reply src/transformers/BookingTransformer.js]: Right now, since there is no "resource" implementation, the resource ID is set to be equivalent to the service ID. This ensures their uniqueness for the time being.

I can't really understand what this code relates to. But the API _does_ give the resource ID. This should be consumed by the front-end. Maybe the only place where the front-end should use the service ID as the resource ID is when it needs to set a `POST /eddbk/v1/bookings` to create a booking.

Comment (XedinUnknown) [reply src/transformers/BookingTransformer.js]: Summary of conversation:

When creating a new booking, because right now there is no Resource implementation, the resource ID has to be deduced from the Service ID. When session selection is implemented in the admin as part of https://github.com/RebelCode/bookings-js/issues/14, this must be changed to use the actual resource ID of the selected service.
