### PR TITLE
fixed deleted service in the calendar view

### LINKED ISSUE #65: Fix bookings page when some service is deleted
### Problem
If the API response contains bookings that have empty service (value of `service` field is `null`, it happens when service is deleted) looks like booking loading never ended.

### Steps to reproduce
1. Create some service.
2. Create booking of that service.
3. Remove the service.
4. Open bookings list page, observe the problem.

### Reason
If `service` field is `null`, booking read transformer fails.

### Solution
Check the `service` field existence in transformer before applying transformation.

### PR DESCRIPTION
**Pull request by romalytvynenko**
Helps to fix #65 in calendar view

### CODE REVIEW

File: src/components/BookingsCalendar.js [hunk 1]
```diff
@@ -140,7 +140,7 @@ export default function (FullCalendar, { mapState, mapMutations }, moment) {
         return Object.assign({}, {
           id: model.id,
           editable: false, // disable dragging and resizing
-          title: model.service.name,
+          title: model.service ? model.service.name : this._('Service not found.'),
```
Comment (XedinUnknown) [inline src/components/BookingsCalendar.js]: Looks like some of the members are not documented in return value doc.
