### PR TITLE
Fixing calendar rendering issues

### LINKED ISSUE #77: Availability calendar rendering issues
### Problem
- All day availabilities are rendered in week view as big rectangle that occupy whole space.
- Availability editor says "last Wednesday" for 29/08/2018 in modal, but calendar UI renderer and backend session generator thinks about it as "fifth Wednesday" and process it accordingly.

### Solution
- Fix all day renderer by using appropriate event flag.
- Write "fifth Wednesday in UI" to not confuse users.

### PR DESCRIPTION
**Pull request by romalytvynenko**
fixes #77

### CODE REVIEW

File: src/components/AvailabilityCalendar.js [hunk 1]
```diff
@@ -516,10 +516,17 @@ export default function (FullCalendar, moment) {
         let eventStart = day.format('YYYY-MM-DD') + 'T' + availabilityStartTime,
           eventEnd = moment.utc(eventStart).add(availabilityDuration, 'seconds').format('YYYY-MM-DD\THH:mm:ss')
 
+        /*
+         * Availability is rendered as all day when "all day" flag explicitly checked in the availability editor,
+         * or when availability's start and end time is midnight on different days.
+         */
+        let allDay = model.isAllDay || (moment(eventStart).format('HH:mm:ss') === '00:00:00' && moment(eventEnd).format('HH:mm:ss') === '00:00:00')
```
Comment (XedinUnknown) [inline src/components/AvailabilityCalendar.js]: How does this expression guarantee that the start and end are on different days?

Comment (romalytvynenko) [reply src/components/AvailabilityCalendar.js]: This is not a validation place. Availability modal will guarantee that this is different days. Here we need to check that this is midnights.
