### PR TITLE
Timezone support for availabilities and in booking editor

### LINKED ISSUE #7: Timezone switching seems to be broken.
When the page is refreshed, the browser parses the date wrongly, so it appears different to how it was when the user saved the download.

Also, calendar is applying local timezone and it looks like broken.

### PR DESCRIPTION
**Pull request by romalytvynenko**
Now timezones are parsed and rendered correctly, fixes #7

### CODE REVIEW

**Comment by romalytvynenko** [comment]
Fixes https://github.com/RebelCode/bookings-js/issues/7

File: src/components/AvailabilityCalendar.js [hunk 1]
```diff
@@ -103,11 +112,30 @@ export default function (FullCalendar, moment) {
...
+
+        el.find('.fc-content')
+          .addClass(`rc-event`)
+          .html(this.getEventMarkup(event))
+      },
+
+      getEventMarkup (event) {
+        const timezone = this.visibleTimezone === this.appConfig.timezone ? '' : this.momentHelpers.timezoneLabel(this.visibleTimezone)
+        return `
+          <div class="rc-event-field rc-event-field--time">${event.start.format('HH:mm')} - ${event.end.format('HH:mm')}</div>
```
Comment (XedinUnknown) [inline src/components/AvailabilityCalendar.js]: Why the double dash (`--`) in the class name?

Comment (romalytvynenko) [reply src/components/AvailabilityCalendar.js]: This is BAM. `--` means modifier. Very suitable for stable UI.

[the remark this answers is not in the document]
Comment (romalytvynenko) [reply src/components/AvailabilityCalendar.js]: Yes, good point. I'm thinking about moving this stuff on Vue, but it will definitely need more time, this is not 30m task, I think.

[the remark this answers is not in the document]
Comment (romalytvynenko) [reply src/components/AvailabilityCalendar.js]: It would be good to make it during refactoring and polishing before release or while beta.

Comment (romalytvynenko) [reply src/components/AvailabilityCalendar.js]: BAM is a semantic naming system for CSS classes. Means block__element--modifier. Two dashes are used to separate modifier from block__element or element. Modifier means that this is styling changes to given block OR element. 

In this case, our block is `rc-event-field` and we apply `time` style modifier for it. Time is more solid than `timezone` style modifier.

Comment (XedinUnknown) [reply src/components/AvailabilityCalendar.js]: What does it mean to "apply a style modifier to a block"?

**Comment by romalytvynenko** [comment]
Please merge ASAP
https://github.com/orgs/RebelCode/projects/2#card-9887687

File: src/components/AvailabilityCalendar.js (hunk 1 above)
Comment (romalytvynenko) [reply src/components/AvailabilityCalendar.js]: It means that you have the semantic reusable block (imagine button). It has some default styles (button is gray). You want to have a sweet button, red and shiny. You creating modifier, `sweet` and apply it to the block (button). As result, you have `button button--sweet`, and you have sweet button.

Comment (XedinUnknown) [reply src/components/AvailabilityCalendar.js]: That I got :) But what I don't get is what changes when the modifier is applied? Does the class name change? How does it change exactly? What is the result of that change?

Comment (romalytvynenko) [reply src/components/AvailabilityCalendar.js]: Text on screen for time can be styled in CSS. It can be bolder, italic whatever needed.

[the remark this answers is not in the document]
Comment (romalytvynenko) [reply src/components/AvailabilityCalendar.js]: https://github.com/orgs/RebelCode/projects/2#card-9888299
